//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectII.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Payment
    {
        [Key]
        public int Id { get; set; }

        public string FullName { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string Email { get; set; }
        [Display(Name = "Donation Amount")]
        [Required(ErrorMessage = "This field is empty")]
        public Nullable<decimal> Amount { get; set; }
        public string Address { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date { get; set; }
    }
}
